#!/usr/bin/env bash

if [[ $1 == 'boot' ]]; then
  jshell --module-path .bach/bin --add-modules com.github.sormuras.bach
  exit $?
fi

if [[ $1 == 'init' ]]; then
  if [[ -z $2 ]]; then
    echo "Usage: bach init VERSION"
    exit 1
  fi
  jshell https://github.com/sormuras/bach-init/raw/main/versions/$2.jshell
  exit $?
fi

java --module-path .bach/bin --module com.github.sormuras.bach "$@"
exit $?
