#!/usr/bin/env bash

set -x

mkdir example && cd example

echo 'Files.copy(URI.create("https://init.java.bach.run").toURL().openStream(), Files.createDirectories(Path.of(".bach")).resolve("init.java"))' | jshell -

java .bach/init.java

.bach/bin/bach --verbose info

cd ..

rm --recursive --force example
