#!/usr/bin/env bash

set -x

wget --no-verbose --force-directories --output-document .bach/init.java https://init.java.bach.run

$JAVA_HOME/bin/java .bach/init.java

export PATH=$PATH:.bach/bin

bach --verbose info
