#!/usr/bin/env bash

set -x

wget --directory-prefix .bach https://raw.githubusercontent.com/sormuras/bach-init/main/init.java

$JAVA_HOME/bin/java .bach/init.java

export PATH=$PATH:.bach/bin

bach --verbose info
